---
development:
  cloud_name: dd6zbr6eq
  api_key: '947964416522987'
  api_secret: 97yitNt0q-CJh7f6SMQMjYXxVis
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: dd6zbr6eq
  api_key: '947964416522987'
  api_secret: 97yitNt0q
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: dd6zbr6eq
  api_key: '947964416522987'
  api_secret: 97yitNt0q-CJh7f6SMQMjYXxVis
  enhance_image_tag: true
  static_image_support: false
